theme: jekyll-theme-minimal
title: qyohs place
description: :-)

#jekyll
lsi: false
safe: true
source: master
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge