theme: jekyll-theme-minimal
title: Z's place
description: nothing to see here :-)

#jekyll
lsi: false
safe: true
source: master
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge